on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: TaintImpact
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Run TaintImpact
        uses: tobiaslue/tainted-code-filtering-action@v0.12
        id: build_taint_impact
        with:
          config-command: "sudo cmake \
            -DCMAKE_CXX_COMPILER=/opt/llvm/bin/clang++1"
          build-command: "sudo make"
          execute-command: "/home/docker/repository/greedy_algorithms/dijkstra"
          clean-command: "sudo make clean"
          default-branch: "master"
          repository-url: "https://github.com/tobiaslue/C-Plus-Plus.git"
